### ISSUE TITLE
Update Documentation for what is in Comcat

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-website#108]
Hi - So CI has loaded their entire catalog (1932-Present) and NM/SE has loaded 2002-present.

So Lisa reminded us to include that information on this list http://earthquake.usgs.gov/data/comcat/data-availability.php
We also have good info on this page that I am not sure if we should reference... 
http://earthquake.usgs.gov/data/comcat/catalog

@paulearle ?

**Comment by lisa-usgs** [comment]
Same as the other comment - once I add the left nav, all the major sections of the ComCat Doc will be linked there, and you'll see that this is just a part of the entire documentation.

I can add this update to the Availability page next week.

**Comment by lisa-usgs** [comment]
The Data Availability content has been updated and will be deployed tomorrow or Monday.  Please check it to make sure that it is up to date as of 2016-06-16.
