### ISSUE TITLE
2002 COUS data file errors

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/earthquake-website#1427]
It seems that the data provided for the USGS 2002 in the following web link are off by a factor of 100 for PGA 2 percent in 50-yr:

https://earthquake.usgs.gov/hazards/hazmaps/conterminous/2002/data.php

I'm not sure what, if anything, should be done at this point with this legacy model other than possibly remove the files that are in error. This issue has been noted for (re)consideration in an update to the NSHMP data management plan.

**Comment by lisa-usgs** [comment]
Is this data also available via the Unified Hazard Tool, like the Alaska data?  I can put a similar note  at the top of this page as I did on the AK page at https://earthquake.usgs.gov/hazards/hazmaps/ak/2007/data.php.  Let me know if that will work.

**Comment by pmpowers-usgs** [comment]
Unfortunately no; we're not supporting models more than two cycles/updates back in the UHT. I'd just comment out the six rows of the table that have a return period listed.

**Comment by lisa-usgs** [comment]
Done and deployed in PR #1436.
