### ISSUE TITLE
Plate Boundary KML file update

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-website#190]
Gavin and I have finally finished our editing and review process for the Plate Boundary KML file that will be published on the web.  We'd like to replace the KML link on the following pages:

http://earthquake.usgs.gov/learn/kml.php
http://earthquake.usgs.gov/regional/nca/1868virtualtour/global.php

with a new KML (sent in email).  Would you be able to push it to the proper directories on the website and make it public?  Let me know if you need anything else!

**Comment by lisa-usgs** [comment]
I've updated the KMZ file on http://earthquake.usgs.gov/learn/kml.php, and Scott will be updating it on http://earthquake.usgs.gov/regional/nca/1868virtualtour/global.php.

**Comment by lisa-usgs** [comment]
This is the description for the plate boundary layer in the ComCat documentation.  What should it be?

Plate Boundaries
This data was acquired from the Peter Bird Plate Boundary Dataset. NOTE: Included plate boundaries were chosen appropriately based on scale.

**Comment by gsmoczyk** [comment]
Proper Plate Boundaries description via Gavin:

**This data was constructed as part of the USGS Seismicity of the Earth Map Series (http://earthquake.usgs.gov/earthquakes/world/seismicity_maps/), modified from the Peter Bird Plate Boundary Model (Bird, G^3, 2003).**

**Comment by lisa-usgs** [comment]
Scott updated the KMZ file in the 1868virtualtour/global.php file, and I updated the description in the ComCat documentation.  The global.php file update is being deployed right now, and the ComCat update will be deployed probably tomorrow or Monday.
