### ISSUE TITLE
Featured Items section for EHP Homepage

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-website#33]
Need code to replace what is used now on the EHP homepage, AND need to update the Admin for it.  Moving the homepage to the new template requires this to be completed.  Lisa is working on the rest of the homepage.

**Comment by jmfee-usgs** [comment]
I thought we already have a solution for featured items, which allows us to manage them as static-ish content:
https://github.com/usgs/earthquake-website/blob/master/src/htdocs/_features.inc.php

**Comment by lisa-usgs** [comment]
Oh, didn’t realize that.  I’ll look at that and may modify the CSS, but it will probably suffice as a temporary solution until we move to Drupal.
Thanks
-Lisa
—



On Aug 21, 2015, at 11:05 AM, Jeremy Fee <notifications@github.com> wrote:

I thought we already have a solution for featured items, which allows us to manage them as static-ish content:
https://github.com/usgs/earthquake-website/blob/master/src/htdocs/_features.inc.php <https://github.com/usgs/earthquake-website/blob/master/src/htdocs/_features.inc.php>

**Comment by lisa-usgs** [comment]
This was deployed with v1.1.0 hazdev-template release.
