### ISSUE TITLE
Scenario page 

### ISSUE THREAD

**Issue by wald-usgs** [usgs/earthquake-website#571]
On scenario interactive maps, the Leaflet/Mapquest? layers "Street" or "Satellite" give errors when selected?
See:  http://earthquake.usgs.gov/scenarios/eventpage/bssc2014829ab_m7p_se#general, for example. Seems to be the case for all the scenarios in comcat. 

David

**Comment by llastowka-usgs** [comment]
Hi - yes mapquest changed something this summer, this is a straightforward fix.  Thank you for using github to record the issue!

**Comment by lisa-usgs** [comment]
I  moved this issue to the shakemap-scenario project - https://github.com/usgs/shakemap-scenarios/issues/25
