### ISSUE TITLE
Add PR Logo to catalog pages/template

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-website#62]
I can't attach the logo here so I put it in slack. Here is the text source

<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   id="svg3336"
   version="1.1"
   inkscape:version="0.91 r13725"
   width="187.5"
   height="50.625"
   viewBox="0 0 187.5 50.625"
   sodipodi:docname="USGS-PRSN_Logo_V1.svg">
  <metadata
     id="metadata3342">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs
     id="defs3340" />
  <sodipodi:namedview
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1"
     objecttolerance="10"
     gridtolerance="10"
     guidetolerance="10"
     inkscape:pageopacity="0"
     inkscape:pageshadow="2"
     inkscape:window-width="1750"
     inkscape:window-height="701"
     id="namedview3338"
     showgrid="false"
     inkscape:zoom="9.4133333"
     inkscape:cx="93.75"
     inkscape:cy="25.3125"
     inkscape:window-x="2015"
     inkscape:window-y="87"
     inkscape:window-maximized="0"
     inkscape:current-layer="svg3336" />
  <image
     width="187.5"
     height="50.625"
     preserveAspectRatio="none"
     xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAAA2CAIAAAANokGgAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAg
AElEQVR4nO1dZ1hU19beZ/rQhqEzgBQBKUEIWJCmwgVMQM29RoKi3sQkatSI7QbFEjGxJLaoiAa4
8VETS2JAYyOCQqQYTGiKCAhSZUZhKAMzTD/fj3XZ30gTkehXeH/4DPvsds5ZZ/W1JRBC4eHhpqam
6P8HBK2dxdUCtZp83Rv5Pw4CIZSTk+Pr6/u6d/KKcOtu7T8Xf9TaVPO6N/J/GWO8QmnDHqxUKikU
CoVCIUkSIUQQxMhtrB+QJEkQBP73ZVaUCJtE/EcjurtRPAO5RDR8wkIIab5peNl/HVQqFZVK7bXQ
X03Noxg2KMMeCS9VqVT+1SSFgRkVpqdXtvQoXhTD51jd3d0ymQz1UNgrEIUIIbVaDTySw+FQqdSX
F4uj+IswTMIiSXL79u25ubkUCkWtVo/snvoFQRAMBoPL5fJ4PB8fn/DwcC0tLTRKUv9T8cKEhTlH
TU1Nfn4+bhxEKg3+7kmS7GsBqNVqCoUCUo9Op+vp6Tk5OQUEBEydOtXGxsbQ0JDFYmnKRM1twFQw
J0w+SnyvHsPhWKQGgAKGrbxTKBTUQ0bwJ0EQKpUKIQT8afz48W+//baPj8+YMWP09PQYDAYwSJCJ
wC/VajXRA9iJQqGg0+maM48geDxecHCwra2tXC6/f//+1atXCYKYMGFCXl7eyC70vxovZRW+PEiS
pNFoKpVKrVbTaDSCIJhMpoGBgYeHx5w5c9zc3Hg8HofDodFoqIcKEUIEQQAJqtVquVwukUju3btX
WVmpVCpVKpWBgYGNjY2trS2Xyx1ZXkUQxLRp0/bt2ycQCHbv3s3n8yMiIkJDQzs6Ojo6OvLy8hYu
XBgZGenq6gobLioqEggENBrN0tLSwcFBJBItXLiwvb191apVAQEBZmZmcAvV1dUpKSnffvutUqkM
Dg7+6KOPSJIUi8UGBgb19fX19fVFRUXNzc3Lly/39vY2NDRECMnl8lmzZpWWlmpuz9jY+MKFC9bW
1gghsVicl5dXVlbm4eHh6empq6uLEFIoFAUFBd9++216ejoMMTExCQoKioqK4nK59fX1IpGIy+U2
NjaWl5dbWFh8/vnnL/W8cnJyyCFDrVarVCqFQjFnzhxNNjP4+xgIoIAzGAwtLS0TE5Pw8PCkpKS8
vLzm5mYwDiQSiVKphEVVKhVsQKFQKBSK1tbW/Pz8TZs2zZo1y9LSks1ma2trM5lMPT29MWPGhISE
xMfHt7W1wSiM30pqTGych/eg9PT0ioqKmpqapkyZghtnzZpVU1OzceNG+NPKyqqoqAjWmjNnDkKI
RqPZ29tv3ry5trZ24sSJ8MRWrlwpFotJknzy5EloaCiMnTFjRnNz84EDB8zNzZlM5uTJk3/88UeF
QvHuu+8ihJhM5u7du7u7u2Hy/fv392LGM2fObGxshKsnTpxgs9kIIV1d3e+//x4ai4qKjIyM8Etx
cXFJT0+XSCSZmZlTpkwBgeDp6ZmYmKhQKE6cODG8p4QQcgyMes0ci0KhmJmZBQcHT58+3cvLy9bW
lsVigd2HEAIFCws4aG9tbS0sLMzNzc3NzS0oKBCJRHQ6HQQiQogkSZVKJZVKBQLBw4cPPT09J0+e
PFK7nThxooeHR1tbm4mJCW785ZdfrKys9PT04M+GhoaOjg7NUUqlsqqq6uuvv7axsYEWtVpdX1+v
VCoRQnK5/PHjxwghDoezatUqIyOjM2fO8Pl8hFB+fv6iRYtu3LgBo2QyWV1dXWFhoaenJ4vFCgsL
S0xMLC8vh6t0On3q1KlXr179+OOP1Wp1ZWVld3c3Qqizs/Pp06fQp7Ozs6WlBX67urqePXvW1dU1
JycnKiqqqakJ2gsLC1evXs1gMF7SlfNShAXKDfyLG4EO8McEMg50HZVKBe1UKtXBwcHX13fixIne
3t7W1tYMBoNCoYAEAWArgUKhyOXy5ubm0tLS4uLin3/+ua6uTl9fPyws7J133oEHd+XKlbq6OuyM
gIF8Pj8tLc3Ly4vBYLzMbWIAD9DX1z906JCZmVlqaiq8s9OnT4eEhAw0ytnZ2dHR8eLFi9euXROJ
RAN143K55ubmCKHPP/9806ZNJSUlJElKpdI9e/Zo2t35+fksFsvT09POzi4gIAAT1qRJk0QiERDT
c0Gn048ePeri4qJWqxMTEzFVASQSyaFDh6KiooYy1UAYYY4FLxULR4IggFaAkTCZTBcXF/ju/f39
bW1t6XQ6kJ1MJqNSqb2mAtoSi8VXr16Nj48vKysDZkChUObNm7dt2zYdHR2SJCUSiZ+f3+bNmysq
KhBCSqUSMzmJRDKCd1dUVNTW1sblcseMGXPw4MH58+efP3/+xIkT7e3t586dG2iUp6cneEZ+/vnn
QSaXSCSdnZ0IoRkzZjg5OSUlJZ08eVIgEOTm5mo+mYaGhvT0dE9PTxqNtnz58uTkZCC7gICAmzdv
Yqk6OKZPnz5p0iSCIEQi0fXr1/t2KCwsBCflsDHCFhPSIAhs3xkYGPj7+3/44YcJCQlpaWnx8fFL
lixxcnICfqtQKBBCbDZbU+SBLoW/1PLy8tzc3K6uLlDwEUJ2dnYsFgshpFAotLS0wsLCFi9ezGaz
aTQak8lECFGpVF1dXXd39170+jLg8/nr1q1rb29HCDGZzICAgEOHDuXk5MyfP7/f/hQKZdKkSTEx
MUOxTJ8+fZqQkCCTySgUip2d3a5duwoKCuLi4uh0ukAg0OwZHx8vFAoRQs7Ozm+//TZCiMVi2djY
9NLlB8HUqVPBaubz+fD8++L+/ftDnK1fjAzHwqIQfoCexOPxjI2N3d3dQ0JCvL299fX1GQwGiE6V
SgU3Bso76hF8mnIdUyeECAmCAKUERqEeKQkckSAINzc3LpfL5/OBmqlUqoWFxaRJk0bQ3aBWq0+f
Pt3c3Lx582ZPT0+4BTc3tyNHjnA4nMTERLxDwLJlywwMDFxcXIY4f0pKipGR0dq1a62trUH73LBh
w5QpU9atW1dSUoK7CYXCX3755f3336fT6RERETdv3gwPD8/JyQGKHwr09fX/at/e8AmL7BNLAV1b
R0fH2Ng4MDBwzpw5Dg4OhoaGTCaT7HFaIoSUSiWIP2BI3d3d3d3dkCtBp9NZLBaLxcIuU7wEsDEq
lQr0BC8VIaRWq+l0OoVCYTKZoEtBHzab/dZbb/F4vBF8ggRByOXyy5cvFxQUREZGLlu2zNHRESHE
4XBWr1596dKlhoYGzf7Hjh2rr69PSkoa4vwKhSI+Pj4vL2/x4sUffPCBlpYWjUYLDAzcs2ePpg7X
3d19/vz5iIgIbW3tGTNmjBs3zs/PLzY2dug3IpfLh955eBg+YalUKvAnAdvQ09NzcHAICQkJCQmx
sbExMjLC7lNQ24Hl0Gg0oCqRSNTQ0FBUVHT58uWqqirQsZhMpqOjY1BQUFBQ0JgxY4BXKRQKIEGQ
rTAt8Aa1Ws1kMsEN9vjx446ODriqr6//4Ycfrlu3bqTUdsBnn31WV1d39uxZPp9/4MCBY8eORUVF
bd++3dzc3MHBgcPh9CIstVqdn5+/d+9ekM4IIVNTU6FQ2IuxAby8vBYtWhQdHV1YWFhYWLh3796V
K1cuW7ZMW1vb19fXzc3t3r17uPPVq1eLi4t9fX2NjY337duXmZn5QtpkWVkZvBoLC4uRfUQYwycs
BoOhp6dnYWFhZWU1bdo0Ly8vGxsb2CgOtgBJYe+8SqVqaWl5/PhxcXFxVlZWSUmJQCDo6urSfNCl
paUZGRkBAQFxcXEuLi5Al31XxzYjQkilUnV2dubk5HR1dbHZbHt7+4iIiA8++EBfX39k3e50Oj0o
KOjixYtgfHV3dycnJ4vF4sTERBaLNVDMND8/f+zYsQghNpu9fPnygwcPtra29tvT29uby+W2tbUh
hGprazdu3NjR0bFlyxZYulfn7777buLEiQwGw9nZeceOHS8Usf3pp58+//xzCwsLHR2dKVOmpKam
9upApVJpNNrL6O/DJCyCIFxdXf38/Ly9vXk8nomJCURXgIfhqAuQhVwul0ql9fX1d+7cuXTpUn19
PfgdKBSKrq4uSZJdXV3QAoytq6vr0qVL48ePt7e3B7HYV5yBmkWlUpVKpVwuz8jI+PXXX+l0+oQJ
E9avX+/j46OlpTXiagRBEJGRkVlZWT/88ANurKqqEovFjx49GkjFqaioAHN1woQJ/v7++/fvH2h+
Ho+3adOmLVu2AOEqFIq8vDyZTNbQ0FBYWNirc1ZWVkVFhZubW3l5+e+//44QolAo4BB5Ltrb2/fs
2bNz504tLa0lS5ZkZWUBNQMoFAr4cfo1GIeI4RNWbGwsZktgWeBIC41GA5tfqVQ2NTWdPHnyjz/+
gLiEUqmcM2dObGzsuHHjlEplbW1tVlbW4cOHa2trgQlhX5dQKFQoFP0Gm1FPrFAsFgsEgmvXrh08
eLCxsdHW1nb16tXTpk2jUqlUKnXEw88kSQoEgvnz51tZWf300091dXVWVlYff/yxSCRavXo1eDWd
nZ1xAYGDgwM8H2tr6xkzZmzYsCEnJwfsPgcHB5BBLBZrzJgxYNBRKJTo6Gg2m52cnFxcXGxlZTV/
/vzGxsaVK1cihLS1td3d3dlstomJydOnT2tqai5cuODi4nLixAmxWIwQMjU19fPzg3lcXV21tbXF
YjHEIWA/HA7H1NT0yZMnCKHDhw+LRKItW7YEBgYmJibu3r0bRK2np+c//vEPIyMj4JTDRv+EBZoK
6nFvaqreqEebBgUI8x7NGDDSUOpLSkqSkpLgocOczs7OdnZ2TCaTyWS6urpaWFgIBII9e/aA6Ycj
ygqFgujJUO27w66urlu3bpWUlKSlpZWWlra1tdFotKampqSkJFtb23HjxuFb0HS6viSePHmyZcuW
zMzM4ODg2NhYkiTZbLZQKIyKivrjjz8QQgsXLnz33XfVajWwqNmzZ48dO5YgCCMjI2tr6+7u7ry8
PDMzs08//XTSpEm1tbVwv9HR0WPHjs3Nzc3Kyjp79mxYWFhsbGx7ezubzRaLxZGRkffu3XN3d1+x
YoWXlxeVSt23b9/Bgwf//PPP5ORkb29vcM17e3t/+umnbDYblnZycjp06FB5efn48eNtbW2hkUKh
HD58OCkpKT09Xa1Wnzx5Mi8v79133/Xz89uxYwefz5dIJCqVKi0tLTc3t1f8YDjIzs5WKBQQjIPA
nFKpbG9vLy0t/fnnn5ubmyE21ytoCP1hoFwu7+7ulkgksDPNuN65c+cMDAw0l9u2bZtEIsGeKolE
cuXKFSzyqFQqnU5nMBhxcXEymQziM1u3bsXkCw/I3t7e1dXVyMgI99fW1qbT6dra2hs3bhQKhTKZ
TCaTwe2MVKxwFEPEf2KFmM0olcrW1taampqHDx9ev369rKxMpVKdOXOGw+GA9q3JPLBrG4Lh1dXV
3t7e3t7eOIYzlB2QJEmj0czNzXV0dIRCIQhTkiR1dXX9/f0HYjYQQJ07d65Kpbp27Vp6erpIJAJN
UyqVnj171tHRMTIykkqlgtI2mo/16vGfNwfyrqCg4N///vedO3eePHkC2py9vT1mEngMkNTDhw+L
ioru3r17586diooKOp1uYWExZcoULIOGAnBNSaVSTecng8FYuHChq6vrQCVAFArFz88P0it8fHwM
DAx++OGHzs5OoKHGxsaEhAR3d3cXF5dRknpd+I/bGiFEkuSff/75ww8/gNRjMplgcMHbAhcU9o+r
1epvvvnmxx9/hKgqhULhcDjY2zT05UHxf/DgAZAFWLnh4eErV67kcDjQp1+WA+Y3jUaztbX917/+
VVlZmZmZiZW8e/fuHTt2bMuWLaampqO09VrwjD6OEzLVanUvLgIcS/MlNTc3t7e347geZDSA/7Nf
75FmGhaoaDC2vr4+IyMDqIrL5S5btiwuLs7a2hrH+HrpdngqnChhYWHx0Ucf6evrkz1ZziqV6sKF
C+fPnwdzFe4IDx/FK8B/UwBmDJgt9X2XmiM1Iy39Cqy+AOrB5qRUKi0vL//qq6/S0tK0tbUnT54c
ExOzfv16Ozs7TDeAXgQBK2L+RKVSAwMDw8LCIEQNDvrW1tYzZ87U19fDF4KzBUdLxl4NXnWiH0mS
CoWiq6urubn56tWrFy5caGxsfOONNyIjI6dPn25tbQ05CwPRMeqvlpAgCENDw48++uj+/ft3795F
PR61srKyI0eOxMXFgZj+z5yjovGV4DUQVm5ublVVlVAo7Ojo8PX1DQgIsLe3t7GxgUwHXP7QrweL
GLiG0d3dfenSpevXr4eoGVTSnjp1ytDQcNGiRZaWlqOs6lXiNaQmCwQCFxeX9957z9bW1traGnIT
sI8KfGD9JlERPbmpkB6I24FidHR0QkNDr127duXKFSyaJRJJfHz8H3/8ERoaOmHCBEg5H8UrwEsR
FqlxRMdQOkPP8PDwmJgYqBvpFXUhNXKaEUKQWQUArdzU1NTf33/GjBmBgYHgMIN20M2NjIw++eST
0tLSmpoaIE0Wi2Vvb//GG2+4uLhYWVmNeCnYKAbCa+BYkDjVbwl1XxlHkqRSqdTT05s3b56vr6+j
o+Mbb7yhra0NEUlNoUmSJIPBmDhxYnBw8MWLF21tbadPn+7h4eHh4WFqago5F4MTlpOTEy5iQQg1
NDTU1dXBbz09PVdXV8xHq6qqemV1jqIXXgNhEc9ioG5gxIG/9J///CeDwWAymeBLw+4GTJpETyUZ
h8P58MMPw8PDnZycTE1NmUwmdMY1PINszNraev369dOmTQM5++uvv77//vtAQEwm09vbOzo6Wl9f
PyUlZffu3WvXrjUyMsKUig9HAddMU1PTl19+qVar9+zZo6OjA74VnFeNU4moVGpeXh6Hw3F1dYV5
SJKsqqrasWPHt99+Cx8DtHd0dOzcufPJkyceHh5Lly5ls9kNDQ2HDx+Gag4qlerv7x8UFMTj8cBM
efz4cWpq6t27d+HG7ezs1qxZo62tjT9FyBJACLW0tBQVFZ0/fx7kg7u7+5IlSzRzQ0QiUWJiYmlp
qaGh4VdffQUPR61WP3r06MsvvxzsTWdnZ4P9f+TIkV5pX3Z2dpAUht1OmnWFSEObNjQ0PH36NPY+
DBIrjIuLw7FCcmBg55NMJpNKpTj2B6vDJXhD8Jjkcjm4FRQKhUwmgyAmxD2hEXo+N1aIqyxVKtXJ
kyc1mdySJUuOHDmC+daCBQukUilJkhKJxN/fHyGkra29aNGi33//vaysjMvl6urq8vn8+Ph4KCLN
zMyEmeHR+fj4ZGdnnzx50srKCl4BSZLFxcU8Hg8hZGlpee3aNWh8/PixJisNDQ2trKzEGc9ubm4p
KSkqlSojIyM4OJjNZgcFBWVmZnZ3d6ekpMBsCCE9Pb2EhASYsKSkhE6n29rabt26tbOzU61WX758
GS+ho6Nz8eJF6FlYWAg5GgBzc/Oqqqra2trly5fjire+cAyMeo7O8TK2OamRxo7nIZ49PK3vEKxX
YVcqQRCg4GONCrtYNcdqXkUafFGzqnYo6iCfz6+qqkI9tUAxMTE4/1MoFEqlUrzurVu3IF8FQywW
nzx5ctmyZc3NzdCSn5+/Y8cOLFI1kZeX99lnn8lkssbGxsTERKlUihAyNjbW0dFBCDU2NsbGxkLd
DofDcXJywgOpVOrx48chYcHS0vLYsWOzZ8++f//+mjVr0tPTu7u7b9y4ER0d3dTU9M477yQkJFhZ
WSGERCJRZmam5gZqamp2796dn59PEMRbb721fPlyaO/q6sIp9r///nt1dTX8NjQ0XLp0aXZ29uzZ
sxMSEgYpZUODV+k8V1oNAk3Gg980ZCIQPfUUqI9swlwKroLrn0KhAKMCXvXkyZP8/PyioiKIOmOJ
CVul0WggPXGZBqzbN3IwECQSyc6dO+vr6xFCNBrts88+mzlz5hDveurUqS4uLtXV1XBcilQq3b59
O6QM9Yvbt29/9913JEleuHABiI/H40HhDUKouroazoMAJoRHhYSEpKWlQUHK1q1bJ0+eTKFQLl26
pJm7fPfu3Vu3bhEEER4evmLFCmjsmxItl8txKtiECRP67lAul4Mwtba23rdvn6Gh4dq1azUrOwbC
YISFyWIYHiCiJx0eBAd+ozjLFCHUt/AI2BLZk3aMmRZ81r/99ltMTIy3t3doaOjt27eB4EY8mw8h
VF5eHhkZCQns+vr6Bw8e9PT0HMrAkJAQKyurzs7ODRs2tLW1KRSKvpmfvXD79m2EUGdn57lz5+DG
586dCyYzLpKmUChz5861tLRECLm5udHp9KKiIoSQiYlJVFQUPOHffvut18wpKSkIISqV+t5772lK
0l7AEg2+pb4Amjt9+vSdO3dWrVqlmWs6CJ5vfgOZvyhtYdKBxBUo9zMxMYESXqy69tKrUI9eCcyp
o6Pj0aNHaWlpGzZsmDlz5sKFC+Pj4/l8PtarNIXdyOL27dtAHAghc3PzxMREXCA/0P16eHiEhYUR
PXXYL7ripUuXwFBwdnb28fGBdblcLhTFjxs3ztnZGSHk6emZk5MDQ4KDg6EUFiGEj5TCgAeFEDIy
Mur38GI2m+3l5RUYGCiXy7OzsxMSEvr2YbFY77333rlz5+rq6k6dOjV0MniOVQjHuWjWRAxlUkwi
KpWKxWIZGBhYWVmFhoYGBAQ4ODjweDxcxaXJDrHKr1QqW1pacnJyrl27VllZ+fDhw87OTpyyrFar
4RvFRhY5QJbpSyIlJcXOzm779u0EQXh5ee3fv//XX3/ttyedTl+zZo2joyO8++GhtLQ0Jydn7ty5
+vr6s2fPTk9PnzFjxuXLl9va2hYvXkyj0RYtWpSenh4cHLxz504YYmFhgYf3La6Xy+VisVhXVxdq
4zQv8Xi8vXv3QiqzQqFYt25damoqcMdeCAsLmzdvnp6enomJSVZWVmJi4hBv5z+EhTUhrOqSJAl1
EC0tLVg2A1/B1IDpTFMeaX6sdDp9/PjxycnJdnZ2xsbGQBB4lKYSBgHEpqammzdvlpSUlJSUVFRU
QHYyPp4Z9XhQsftgBKuc+0Iqle7evdvBwWHevHl0On3mzJljxozpK3EQQkql8syZM66urmvXrn2Z
5c6ePQtJZnPnzt27d6+np+emTZtqamoiIiJ0dHR8fX2DgoL4fD4+r+E56nOPHkL2yZATCAQZGRnH
jx83NDSUSCQymaxfqkII3b9/XywW//3vf9fR0dm2bVt5eTkYsM+9nWc4EJfLpdPpmB/QaDSRSFRa
WgrRN6z6AEGAhqSpFENmMyY+mNPGxsbHx4fH44FlhxCSy+U40Vkmk7W3txcXFycmJq5atWrBggVb
tmz5/vvvi4uLZTIZrh/Ezguyx9+BepJ8/iJ2BVAqlRs3boRiFRqN9uabb/bbjSTJpqamvXv3pqWl
4cYhFsxo4ubNm6DYGRkZxcXFNTU1PX36tLy8HCLrPB7v66+/vnXrFqaSGzduYBPV1ta212w6Ojog
KLu6uiorKzUvqdVqqDVSq9VaWloxMTGazE8T5eXlMTExUAVkZmZ24MABsDGfi/9mOWq12s7ODo7Z
QD1UolAoTp8+nZ2dDQ4b7GaEc4JAREKhqZmZma6ubi9THzsnwY2kWXfa1tZWUFBw5MiR1atXR0ZG
rl+//vz582VlZWDAExp1GZoa2KtHU1PTypUrwQ4aXBMQiUS3b9/G+/zggw9edC1Q4eEp/e1vf7t0
6RJCiM/nZ2VlIYTgIWvSbk1NDTYOAgMDe82GWwoKCoA0NSGVSr/44ovi4mKEEBwVAW6Ovqiqqlqx
YkVLSwtBEJ6enrt27cI5mIPgmXwsW1vb8ePHg0cAoFKpSkpK1q1bB1lTDx48aGhoePDgwfHjxx8+
fMjhcMaOHRsREbF169ajR49OnToVPSsKMS8BpUqhUDQ1Nd24cePo0aNLly6dPXv2li1bzp49W1tb
C8wJ2A/o+zDw1ZNUXw9LXV3dypUre5310y+OHDkCiayzZs2C6vsXgkqlSk1NBW09NzcXPFUIoeTk
ZKlUqlarz5w5o+ky6O7u3rZtG5RzTZs2TZMyOBwOnDxTXV29efPmfpcTCoUbNmyAUoOIiAhw2/aL
oqKi6OhoqLOdO3fuhg0bnls//YyOxeVyFy5cWFZWJhAIgMGAQlNTU/PNN98YGhoaGBiAukOn02fN
mgWnBkB1OYPBAIGFXwzmOiqVCo5Bq6iouHr16v3791tbWyUSCc47RRraG+xHk10NfgMjCIIgtLW1
7e3tzc3NoRADbyYnJ2fjxo0HDhzQ7A91QajnRGeCIKRSqZ6enp+f386dO3/55RfNzkwmE1cz29vb
9xsqRQj9+eefd+/eDQoKSk1NBe8oQkggEBQVFY0bN+769eu9Hsj169djY2N37doVGhq6YMGCEydO
SKVSCACMHz++qalp48aNwG6pVKqZmRmMYrFYTCZToVCkp6efOnXq008/ZTKZmzZtqqysBD8OluNQ
59LV1ZWamurn5/fJJ5/Q6fTo6GihUJicnPycY0iys7Ox+iIWi48dOzZhwgQdHR2sa4Nj08jI6M03
34yKitq/f39hYWFnZyd8RuC6xMET+A11XTU1Nenp6bt27QoMDLSwsNDS0gJfJXgvcb0XLkvESjpu
6XfDdDr9m2++geKwweNCfTFISCcyMjIjI0OhUAgEggMHDhgbG/dadNWqVV9//TX8uWbNmlu3buEv
58aNG3FxcVu3bs3Ozu7s7CRJcvHixXjstGnTjh8/DmdDkiTJ5/N37dqleSygJhYsWFBTU6OZF0QQ
xIoVKzIzM8G/1RcTJ048ceLEgwcPTp069eWXX164cKGioiIpKcnDwwM6WFpafvHFF5WVlbABpVL5
/fffR0REIITMzc1xrKmhoSE6OnrHjh0tLS3Q0tnZefToUTc3N0dHx/Pnz+PHqFAoMjIy+vWpIoQc
A6N6/ydNcrlcpVLV19dfuXKlvr5eIpHI5XIajaarq+vi4jJlyhRLS0s4MhSMNdgnj5EAAAIjSURB
VBiFq6xUKlVXV1dDQ0NVVVV+fv6dO3eqq6tFIhGQIHo2aDNsMBiMPXv2LFu2bKD8+kFw627t3Nlv
P6190PeSoaEhdgshhAQCQS8XLtw4fKbgNBlkIaFQiA/q4HA4fSNrfefHq3C5XBBwGFpaWlAcO9By
bDZbV1cXGCdYRfDl4zmNjY17Pavu7m4Qu1wuF4tRpVKJgxYAkiRbW1tJkjQ0NOz1qbe1tXV1dfXd
TD9nkMLa9vb2n3zyiUKhAA4EDnEGg0Gn04GGyJ6TZHA4RSwW8/n8hw8f5ubm3rp1q7a2tqOjAzLN
CY2C5penKvSs4jWCVqFQKBzkzSGE5HI5PgBoKCoXBhyrPMTOcrm8F1UhhKAYeJBRcBrUIHMO5FBA
CLW1tQ3Fn97Y2PjcPhi9CQtHUeh0OpPJxD5JrBBgRQEuAT1Bqfu9e/ceP34sFArJHl8XODNxtf4I
auJYAyMGLsMfxWtEPxyL1EgQgEaIyZA9eQpgmDQ3NxcUFOTk5Dx69Ki6uhr4E4vFsrCwIJ7Nf6L0
HEQz7HBHL9DpdDim5iXnGcVfh344Vq+wMf6t6TtACKnVamtra6jmQz12ZS/LrtfM5IukMg8CCoUC
JWKDKPijeL3oJ1b43FcFHXg8Hk4ie/XAvlby2XyvUfwPwYilJr/iV9srCvZCQUMtA3O9HnNpFH8F
GFp6BEJo5syZ/3v/s/EX5ViC1s7iKv7ofzb+V+O/AFKP4Wy+rNsrAAAAAElFTkSuQmCC
"
     id="image3344"
     x="0"
     y="0" />
</svg>

**Comment by lisa-usgs** [comment]
completed
