### ISSUE TITLE
New Significant Earthquakes page needs JS for YEAR input

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-website#66]
The new Significant Earthquakes webpage is complete except for the YEAR input to select a different year than the default current year.  Also, can it be coded so that the new "Top 10" page can pass a year to it?  The input box should not span the entire width, and as soon as we have documentation for "Significant", the commented lines will be uncommented with the appropriate link.

Significant Earthquakes - http://static-earthquake.cr.usgs.gov/earthquakes/browse/significant.php
"Top 10" - http://static-earthquake.cr.usgs.gov/earthquakes/browse/

I'll need to modify the left nav before this goes live since 2 of the 5 items are still on the old server... and the IA for the Earthquakes section is not final anyway.

**Comment by jdbrown-USGS** [comment]
- Fixed form and added some basic styles.
