### ISSUE TITLE
ENS Links

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-website#914]
Links for ENS should be migrated over to the `earthquake` domain coinciding with the ENS interface migration.

- /data/comcat/index.php
- /data/pager/faq.php
- /earthquakes/feed/_navigation.inc.php
- /earthquakes/feed/index.php
- /earthquakes/ted/index.php
- /monitoring/anss/products.php

**Comment by jmfee-usgs** [comment]
These pages should link to "https://earthquake.usgs.gov/ens", which redirects to the appropriate location if needed.

**Comment by lisa-usgs** [comment]
What is the target date for deploying the new ENS?

**Comment by emartinez-usgs** [comment]
@ehunter-usgs Thoughts on when this might be deployed?
@lisa Soon; but I don't have a better answer for this yet. ^^
@jmfee-usgs The link should be relative to the site root, for example the source code should read `/ens/...` rather than `https://earthquake.usgs.gov/ens/...`. These will be treated as the same on the rendered page.

**Comment by lisa** [comment]
@lisa-usgs ^^ 

;-)

**Comment by ehunter-usgs** [comment]
@emartinez-usgs @lisa-usgs, I am deploying now, but I am deploying to `/earthquake/ens` for testing. I am not sure when we plan on switching users to the new ENS which will be at the url that jeremy mentioned https://earthquake.usgs.gov/ens

**Comment by jmfee-usgs** [comment]
Alternatively, @lisa what do you think, ENS could be at https://earthquake.usgs.gov/earthquakes/ens and update the "/ens" short url to redirect to the new location

**Comment by lisa-usgs** [comment]
I think keeping the URL as /ens is best.

**Comment by lisa-usgs** [comment]
Just let me know when you know when deployment is so that I can coordinate updating the links on the website.  Thanks.

**Comment by jmfee-usgs** [comment]
@lisa-usgs : since the mentioned URL already redirects to the ENS location, you don't need to wait until the application is deployed to update the links.

**Comment by lisa-usgs** [comment]
Done.
